# Generated by Django 5.0.5 on 2024-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="platform",
            field=models.CharField(default=104, max_length=50),
            preserve_default=False,
        ),
    ]
