# Generated by Django 5.0.5 on 2024-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="classification",
            field=models.CharField(default="經濟", max_length=50),
        ),
    ]
