# Generated by Django 5.0.5 on 2024-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="National_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("population", models.CharField(max_length=100)),
                ("populationGrowth_annualGrowthRate", models.CharField(max_length=100)),
                ("AverageExchange_rate", models.CharField(max_length=100)),
                ("EconomicGrowth_annualGrowthRate", models.CharField(max_length=100)),
                (
                    "Domestic_Grossproduction_GDP_nominalValue_millionYuan",
                    models.CharField(max_length=100),
                ),
                (
                    "Domestic_Grossproduction_GDP_annualGrowthRate",
                    models.CharField(max_length=100),
                ),
                ("AveragePersonalGDP", models.CharField(max_length=100)),
                ("AveragePersonalGDP_rate", models.CharField(max_length=100)),
                (
                    "GrossNationalIncomeGNI_nominalValue_millionYuan",
                    models.CharField(max_length=100),
                ),
                (
                    "GrossNationalIncomeGNI_annualGrowthRate",
                    models.CharField(max_length=100),
                ),
                (
                    "AveragePersonalGNI_nominalValue_millionYuan",
                    models.CharField(max_length=100),
                ),
                ("AveragePersonalGNI_rate", models.CharField(max_length=100)),
                (
                    "NationalIncome_nominalValue_millionYuan",
                    models.CharField(max_length=100),
                ),
                ("NationalIncome_annualGrowthRate", models.CharField(max_length=100)),
                (
                    "AverageIncomePerson_nominalValue_millionYuan",
                    models.CharField(max_length=100),
                ),
                (
                    "AverageIncomePerson_annualGrowthRate",
                    models.CharField(max_length=100),
                ),
            ],
            options={
                "db_table": "national_data",
            },
        ),
    ]
